-- ============================================================
-- NIRNAY — Migration 001
-- Initial user-owned financial data schema
--
-- Authentication authority:
--   Firebase Authentication
--
-- Identity boundary:
--   user_id = Firebase UID
--
-- Authorization:
--   Supabase RLS using auth.jwt() ->> 'sub'
-- ============================================================


-- ============================================================
-- 1. Helper function: automatically maintain updated_at
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ============================================================
-- 2. User profiles
-- ============================================================

create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,

  user_id text not null unique,

  full_name text,
  email text,
  phone text,
  avatar_url text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================
-- 3. Financial profiles
-- ============================================================

create table if not exists public.financial_profiles (
  id bigint generated by default as identity primary key,

  user_id text not null unique
    references public.user_profiles(user_id)
    on delete cascade,

  monthly_income numeric(14,2),
  monthly_expenses numeric(14,2),
  monthly_investment_budget numeric(14,2),
  annual_insurance_budget numeric(14,2),

  risk_profile text
    check (
      risk_profile is null
      or risk_profile in (
        'conservative',
        'moderate',
        'aggressive'
      )
    ),

  financial_experience text
    check (
      financial_experience is null
      or financial_experience in (
        'beginner',
        'intermediate',
        'advanced'
      )
    ),

  primary_goals text[] not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint financial_profile_income_non_negative
    check (
      monthly_income is null
      or monthly_income >= 0
    ),

  constraint financial_profile_expenses_non_negative
    check (
      monthly_expenses is null
      or monthly_expenses >= 0
    ),

  constraint financial_profile_investment_budget_non_negative
    check (
      monthly_investment_budget is null
      or monthly_investment_budget >= 0
    ),

  constraint financial_profile_insurance_budget_non_negative
    check (
      annual_insurance_budget is null
      or annual_insurance_budget >= 0
    )
);


-- ============================================================
-- 4. Insurance policies
-- ============================================================

create table if not exists public.insurance_policies (
  id bigint generated by default as identity primary key,

  user_id text not null
    references public.user_profiles(user_id)
    on delete cascade,

  policy_type text not null
    check (
      policy_type in (
        'health',
        'motor',
        'life',
        'other'
      )
    ),

  provider text not null,
  policy_name text not null,

  policy_number text,

  premium_amount numeric(14,2),
  premium_frequency text
    check (
      premium_frequency is null
      or premium_frequency in (
        'monthly',
        'quarterly',
        'half_yearly',
        'yearly',
        'one_time'
      )
    ),

  sum_insured numeric(16,2),

  start_date date,
  renewal_date date,

  status text not null default 'active'
    check (
      status in (
        'active',
        'expired',
        'cancelled',
        'pending'
      )
    ),

  metadata jsonb not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint insurance_premium_non_negative
    check (
      premium_amount is null
      or premium_amount >= 0
    ),

  constraint insurance_sum_insured_non_negative
    check (
      sum_insured is null
      or sum_insured >= 0
    )
);


-- ============================================================
-- 5. Investments
-- ============================================================

create table if not exists public.investments (
  id bigint generated by default as identity primary key,

  user_id text not null
    references public.user_profiles(user_id)
    on delete cascade,

  investment_type text not null
    check (
      investment_type in (
        'mutual_fund',
        'sip',
        'stock',
        'etf',
        'fd',
        'nps',
        'other'
      )
    ),

  provider text,
  scheme_name text not null,

  amount numeric(14,2),

  frequency text
    check (
      frequency is null
      or frequency in (
        'monthly',
        'quarterly',
        'yearly',
        'one_time'
      )
    ),

  start_date date,

  status text not null default 'active'
    check (
      status in (
        'active',
        'paused',
        'completed',
        'cancelled'
      )
    ),

  metadata jsonb not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint investment_amount_non_negative
    check (
      amount is null
      or amount >= 0
    )
);


-- ============================================================
-- 6. Financial goals
-- ============================================================

create table if not exists public.financial_goals (
  id bigint generated by default as identity primary key,

  user_id text not null
    references public.user_profiles(user_id)
    on delete cascade,

  name text not null,

  goal_type text not null default 'custom'
    check (
      goal_type in (
        'emergency_fund',
        'retirement',
        'house',
        'car',
        'education',
        'travel',
        'custom'
      )
    ),

  target_amount numeric(16,2) not null,
  current_amount numeric(16,2) not null default 0,

  target_date date,

  priority text not null default 'medium'
    check (
      priority in (
        'low',
        'medium',
        'high'
      )
    ),

  status text not null default 'active'
    check (
      status in (
        'active',
        'completed',
        'paused',
        'cancelled'
      )
    ),

  metadata jsonb not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint financial_goal_target_positive
    check (target_amount > 0),

  constraint financial_goal_current_non_negative
    check (current_amount >= 0)
);


-- ============================================================
-- 7. Watchlist
-- ============================================================

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,

  user_id text not null
    references public.user_profiles(user_id)
    on delete cascade,

  product_type text not null
    check (
      product_type in (
        'insurance',
        'mutual_fund',
        'investment',
        'other'
      )
    ),

  product_id text not null,

  created_at timestamptz not null default now(),

  constraint watchlist_unique_product_per_user
    unique (
      user_id,
      product_type,
      product_id
    )
);


-- ============================================================
-- 8. Alerts
-- ============================================================

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,

  user_id text not null
    references public.user_profiles(user_id)
    on delete cascade,

  alert_type text not null
    check (
      alert_type in (
        'insurance_renewal',
        'premium_payment',
        'sip_reminder',
        'portfolio_event',
        'goal_progress',
        'product_update',
        'system',
        'other'
      )
    ),

  title text not null,
  message text not null,

  severity text not null default 'info'
    check (
      severity in (
        'info',
        'warning',
        'important',
        'critical'
      )
    ),

  scheduled_for timestamptz,
  read_at timestamptz,

  metadata jsonb not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================
-- 9. Financial calendar
-- ============================================================

create table if not exists public.financial_calendar (
  id bigint generated by default as identity primary key,

  user_id text not null
    references public.user_profiles(user_id)
    on delete cascade,

  event_type text not null
    check (
      event_type in (
        'insurance_renewal',
        'premium_payment',
        'sip',
        'goal_milestone',
        'investment_review',
        'other'
      )
    ),

  title text not null,
  description text,

  event_date date not null,

  status text not null default 'upcoming'
    check (
      status in (
        'upcoming',
        'completed',
        'skipped',
        'cancelled'
      )
    ),

  metadata jsonb not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ============================================================
-- 10. Indexes
-- ============================================================

create index if not exists idx_financial_profiles_user_id
  on public.financial_profiles(user_id);

create index if not exists idx_insurance_policies_user_id
  on public.insurance_policies(user_id);

create index if not exists idx_insurance_policies_renewal_date
  on public.insurance_policies(user_id, renewal_date);

create index if not exists idx_investments_user_id
  on public.investments(user_id);

create index if not exists idx_financial_goals_user_id
  on public.financial_goals(user_id);

create index if not exists idx_financial_goals_target_date
  on public.financial_goals(user_id, target_date);

create index if not exists idx_watchlist_user_id
  on public.watchlist(user_id);

create index if not exists idx_alerts_user_id
  on public.alerts(user_id);

create index if not exists idx_alerts_unread
  on public.alerts(user_id, read_at)
  where read_at is null;

create index if not exists idx_financial_calendar_user_id
  on public.financial_calendar(user_id);

create index if not exists idx_financial_calendar_event_date
  on public.financial_calendar(user_id, event_date);


-- ============================================================
-- 11. Updated-at triggers
-- ============================================================

drop trigger if exists set_user_profiles_updated_at
on public.user_profiles;

create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row
execute function public.set_updated_at();


drop trigger if exists set_financial_profiles_updated_at
on public.financial_profiles;

create trigger set_financial_profiles_updated_at
before update on public.financial_profiles
for each row
execute function public.set_updated_at();


drop trigger if exists set_insurance_policies_updated_at
on public.insurance_policies;

create trigger set_insurance_policies_updated_at
before update on public.insurance_policies
for each row
execute function public.set_updated_at();


drop trigger if exists set_investments_updated_at
on public.investments;

create trigger set_investments_updated_at
before update on public.investments
for each row
execute function public.set_updated_at();


drop trigger if exists set_financial_goals_updated_at
on public.financial_goals;

create trigger set_financial_goals_updated_at
before update on public.financial_goals
for each row
execute function public.set_updated_at();


drop trigger if exists set_alerts_updated_at
on public.alerts;

create trigger set_alerts_updated_at
before update on public.alerts
for each row
execute function public.set_updated_at();


drop trigger if exists set_financial_calendar_updated_at
on public.financial_calendar;

create trigger set_financial_calendar_updated_at
before update on public.financial_calendar
for each row
execute function public.set_updated_at();


-- ============================================================
-- 12. Enable Row Level Security
-- ============================================================

alter table public.user_profiles
  enable row level security;

alter table public.financial_profiles
  enable row level security;

alter table public.insurance_policies
  enable row level security;

alter table public.investments
  enable row level security;

alter table public.financial_goals
  enable row level security;

alter table public.watchlist
  enable row level security;

alter table public.alerts
  enable row level security;

alter table public.financial_calendar
  enable row level security;


-- ============================================================
-- 13. RLS — user_profiles
-- ============================================================

drop policy if exists "Users can select their own profile"
on public.user_profiles;

create policy "Users can select their own profile"
on public.user_profiles
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert their own profile"
on public.user_profiles;

create policy "Users can insert their own profile"
on public.user_profiles
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can update their own profile"
on public.user_profiles;

create policy "Users can update their own profile"
on public.user_profiles
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete their own profile"
on public.user_profiles;

create policy "Users can delete their own profile"
on public.user_profiles
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


-- ============================================================
-- 14. RLS — financial_profiles
-- ============================================================

drop policy if exists "Users can select their own financial profile"
on public.financial_profiles;

create policy "Users can select their own financial profile"
on public.financial_profiles
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert their own financial profile"
on public.financial_profiles;

create policy "Users can insert their own financial profile"
on public.financial_profiles
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can update their own financial profile"
on public.financial_profiles;

create policy "Users can update their own financial profile"
on public.financial_profiles
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete their own financial profile"
on public.financial_profiles;

create policy "Users can delete their own financial profile"
on public.financial_profiles
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


-- ============================================================
-- 15. RLS — insurance_policies
-- ============================================================

drop policy if exists "Users can select their own insurance policies"
on public.insurance_policies;

create policy "Users can select their own insurance policies"
on public.insurance_policies
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert their own insurance policies"
on public.insurance_policies;

create policy "Users can insert their own insurance policies"
on public.insurance_policies
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can update their own insurance policies"
on public.insurance_policies;

create policy "Users can update their own insurance policies"
on public.insurance_policies
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete their own insurance policies"
on public.insurance_policies;

create policy "Users can delete their own insurance policies"
on public.insurance_policies
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


-- ============================================================
-- 16. RLS — investments
-- ============================================================

drop policy if exists "Users can select their own investments"
on public.investments;

create policy "Users can select their own investments"
on public.investments
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert their own investments"
on public.investments;

create policy "Users can insert their own investments"
on public.investments
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can update their own investments"
on public.investments;

create policy "Users can update their own investments"
on public.investments
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete their own investments"
on public.investments;

create policy "Users can delete their own investments"
on public.investments
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


-- ============================================================
-- 17. RLS — financial_goals
-- ============================================================

drop policy if exists "Users can select their own financial goals"
on public.financial_goals;

create policy "Users can select their own financial goals"
on public.financial_goals
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert their own financial goals"
on public.financial_goals;

create policy "Users can insert their own financial goals"
on public.financial_goals
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can update their own financial goals"
on public.financial_goals;

create policy "Users can update their own financial goals"
on public.financial_goals
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete their own financial goals"
on public.financial_goals;

create policy "Users can delete their own financial goals"
on public.financial_goals
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


-- ============================================================
-- 18. RLS — watchlist
-- ============================================================

drop policy if exists "Users can select their own watchlist"
on public.watchlist;

create policy "Users can select their own watchlist"
on public.watchlist
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert into their own watchlist"
on public.watchlist;

create policy "Users can insert into their own watchlist"
on public.watchlist
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete from their own watchlist"
on public.watchlist;

create policy "Users can delete from their own watchlist"
on public.watchlist
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


-- ============================================================
-- 19. RLS — alerts
-- ============================================================

drop policy if exists "Users can select their own alerts"
on public.alerts;

create policy "Users can select their own alerts"
on public.alerts
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert their own alerts"
on public.alerts;

create policy "Users can insert their own alerts"
on public.alerts
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can update their own alerts"
on public.alerts;

create policy "Users can update their own alerts"
on public.alerts
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete their own alerts"
on public.alerts;

create policy "Users can delete their own alerts"
on public.alerts
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


-- ============================================================
-- 20. RLS — financial_calendar
-- ============================================================

drop policy if exists "Users can select their own calendar events"
on public.financial_calendar;

create policy "Users can select their own calendar events"
on public.financial_calendar
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can insert their own calendar events"
on public.financial_calendar;

create policy "Users can insert their own calendar events"
on public.financial_calendar
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can update their own calendar events"
on public.financial_calendar;

create policy "Users can update their own calendar events"
on public.financial_calendar
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);


drop policy if exists "Users can delete their own calendar events"
on public.financial_calendar;

create policy "Users can delete their own calendar events"
on public.financial_calendar
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);