-- ============================================================
-- NIRNAY — Migration 002
-- Product Catalog: Insurance Products & Mutual Funds
--
-- Classification: REFERENCE / CATALOG DATA (not user-owned)
-- Provenance: demo/reference data — clearly labeled
-- ============================================================


-- ============================================================
-- 1. Insurance Products
-- ============================================================

create table if not exists public.insurance_products (
  id bigint generated by default as identity primary key,

  product_key text not null unique,
  product_type text not null
    check (
      product_type in (
        'health',
        'motor',
        'life'
      )
    ),

  provider text not null,
  product_name text not null,
  tagline text,

  base_premium numeric(14,2),
  premium_frequency text not null default 'yearly'
    check (
      premium_frequency in (
        'monthly',
        'quarterly',
        'half_yearly',
        'yearly',
        'one_time'
      )
    ),

  sum_insured_min numeric(16,2),
  sum_insured_max numeric(16,2),
  sum_insured_default numeric(16,2),

  entry_age_min integer,
  entry_age_max integer,

  features jsonb not null default '{}',
  coverage_details jsonb not null default '{}',
  exclusions text[] not null default '{}',
  eligibility_criteria text[] not null default '{}',

  data_classification text not null default 'REFERENCE_DEMO'
    check (
      data_classification in (
        'VERIFIED',
        'USER_PROVIDED',
        'CALCULATED',
        'AI_GENERATED',
        'REFERENCE_DEMO'
      )
    ),

  source text not null default 'NIRNAY_REFERENCE_DATA',
  source_url text,
  last_updated_at date not null default current_date,
  retrieved_at timestamptz not null default now(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint insurance_product_base_premium_non_negative
    check (
      base_premium is null
      or base_premium >= 0
    ),

  constraint insurance_product_sum_insured_positive
    check (
      sum_insured_min is null or sum_insured_min > 0
    ),

  constraint insurance_product_sum_insured_order
    check (
      sum_insured_min is null
      or sum_insured_max is null
      or sum_insured_min <= sum_insured_max
    )
);


-- ============================================================
-- 2. Mutual Funds
-- ============================================================

create table if not exists public.mutual_funds (
  id bigint generated by default as identity primary key,

  product_key text not null unique,

  provider text not null,
  scheme_name text not null,
  scheme_code text,

  fund_category text not null
    check (
      fund_category in (
        'equity',
        'debt',
        'hybrid',
        'index',
        'elss',
        'liquid',
        'gold',
        'other'
      )
    ),

  sub_category text,

  risk_level text not null
    check (
      risk_level in (
        'low',
        'moderately_low',
        'moderate',
        'moderately_high',
        'high',
        'very_high'
      )
    ),

  nav numeric(14,4),
  nav_date date,

  expense_ratio numeric(6,3),

  returns_1y numeric(8,3),
  returns_3y numeric(8,3),
  returns_5y numeric(8,3),

  sip_min_amount numeric(14,2),
  sip_frequency text not null default 'monthly'
    check (
      sip_frequency in (
        'monthly',
        'quarterly',
        'yearly',
        'one_time'
      )
    ),

  lumpsum_min_amount numeric(14,2),

  fund_manager text,
  inception_date date,
  aum_cr numeric(18,2),

  exit_load text,
  lock_in_period_months integer,

  features jsonb not null default '{}',
  benchmark text,

  data_classification text not null default 'REFERENCE_DEMO'
    check (
      data_classification in (
        'VERIFIED',
        'USER_PROVIDED',
        'CALCULATED',
        'AI_GENERATED',
        'REFERENCE_DEMO'
      )
    ),

  source text not null default 'NIRNAY_REFERENCE_DATA',
  source_url text,
  last_updated_at date not null default current_date,
  retrieved_at timestamptz not null default now(),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint mutual_fund_sip_min_non_negative
    check (
      sip_min_amount is null or sip_min_amount >= 0
    ),

  constraint mutual_fund_lumpsum_min_non_negative
    check (
      lumpsum_min_amount is null or lumpsum_min_amount >= 0
    ),

  constraint mutual_fund_nav_positive
    check (
      nav is null or nav > 0
    )
);


-- ============================================================
-- 3. Indexes for Product Tables
-- ============================================================

create index if not exists idx_insurance_products_type
  on public.insurance_products(product_type);

create index if not exists idx_insurance_products_provider
  on public.insurance_products(provider);

create index if not exists idx_insurance_products_base_premium
  on public.insurance_products(product_type, base_premium);

create index if not exists idx_mutual_funds_category
  on public.mutual_funds(fund_category);

create index if not exists idx_mutual_funds_risk_level
  on public.mutual_funds(risk_level);

create index if not exists idx_mutual_funds_sip_min
  on public.mutual_funds(sip_min_amount);

create index if not exists idx_mutual_funds_returns_1y
  on public.mutual_funds(returns_1y desc nulls last);


-- ============================================================
-- 4. Updated-at Triggers for Product Tables
-- ============================================================

drop trigger if exists set_insurance_products_updated_at
on public.insurance_products;

create trigger set_insurance_products_updated_at
before update on public.insurance_products
for each row
execute function public.set_updated_at();


drop trigger if exists set_mutual_funds_updated_at
on public.mutual_funds;

create trigger set_mutual_funds_updated_at
before update on public.mutual_funds
for each row
execute function public.set_updated_at();


-- ============================================================
-- 5. RLS for Product Tables (catalog = publicly readable,
--    write restricted to service role only)
-- ============================================================

alter table public.insurance_products
  enable row level security;

alter table public.mutual_funds
  enable row level security;


drop policy if exists "Catalog is readable by all authenticated users"
on public.insurance_products;

create policy "Catalog is readable by all authenticated users"
on public.insurance_products
for select
to authenticated
using (true);


drop policy if exists "Catalog is readable by all authenticated users"
on public.mutual_funds;

create policy "Catalog is readable by all authenticated users"
on public.mutual_funds
for select
to authenticated
using (true);


-- ============================================================
-- 6. Seed: Health Insurance Reference (Demo) Data
-- ============================================================

insert into public.insurance_products (
  product_key, product_type, provider, product_name, tagline,
  base_premium, premium_frequency,
  sum_insured_min, sum_insured_max, sum_insured_default,
  entry_age_min, entry_age_max,
  features, coverage_details, exclusions, eligibility_criteria,
  data_classification, source, source_url
) values
(
  'hlt-niva-bupa-reassure-2026', 'health', 'Niva Bupa', 'ReAssure 2.0',
  'Comprehensive family floater with no claim bonus booster',
  12499.00, 'yearly',
  300000, 2000000, 1000000,
  18, 65,
  jsonb_build_object(
    'room_rent_limit', 'No limit',
    'pre_existing_coverage_months', 24,
    'maternity_cover', true,
    'opd_cover', true,
    'no_claim_bonus_pct', 50,
    'restore_benefit', true,
    'free_health_checkup', true
  ),
  jsonb_build_object(
    'in_patient_hospitalization', true,
    'pre_hospitalization_days', 60,
    'post_hospitalization_days', 180,
    'day_care_procedures', true,
    'domiciliary', true,
    'organ_donor', true
  ),
  ARRAY[
    'Pre-existing conditions for first 24 months',
    'Cosmetic treatments excluded',
    'Alternative medicine restricted'
  ],
  ARRAY[
    'Entry age 18 to 65 years',
    'Lifelong renewability',
    '24 months pre-existing waiting period'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
),
(
  'hlt-hdfc-ergo-optima-restore-2026', 'health', 'HDFC Ergo', 'Optima Restore',
  'Auto-restore sum insured after any claim',
  13850.00, 'yearly',
  500000, 3000000, 1500000,
  18, 65,
  jsonb_build_object(
    'room_rent_limit', '1% of SI per day',
    'pre_existing_coverage_months', 36,
    'maternity_cover', false,
    'opd_cover', false,
    'no_claim_bonus_pct', 100,
    'restore_benefit', true,
    'free_health_checkup', true
  ),
  jsonb_build_object(
    'in_patient_hospitalization', true,
    'pre_hospitalization_days', 60,
    'post_hospitalization_days', 180,
    'day_care_procedures', true,
    'domiciliary', true,
    'organ_donor', true
  ),
  ARRAY[
    'Pre-existing conditions for first 36 months',
    'Maternity not covered in base plan',
    'War-related injuries excluded'
  ],
  ARRAY[
    'Entry age 18 to 65 years',
    '36 months pre-existing waiting period',
    'Room rent capped at 1% of SI'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
),
(
  'hlt-star-health-comprehensive-2026', 'health', 'Star Health', 'Comprehensive',
  'Wide hospital network with direct claim settlement',
  11299.00, 'yearly',
  200000, 2500000, 1000000,
  18, 65,
  jsonb_build_object(
    'room_rent_limit', '2% of SI per day',
    'pre_existing_coverage_months', 48,
    'maternity_cover', true,
    'opd_cover', true,
    'no_claim_bonus_pct', 25,
    'restore_benefit', false,
    'free_health_checkup', true,
    'hospital_cash_per_day', 1000
  ),
  jsonb_build_object(
    'in_patient_hospitalization', true,
    'pre_hospitalization_days', 60,
    'post_hospitalization_days', 120,
    'day_care_procedures', true,
    'domiciliary', false,
    'organ_donor', true
  ),
  ARRAY[
    'Pre-existing conditions for first 48 months',
    'Domiciliary treatment excluded in base',
    'Room rent capped at 2% of SI'
  ],
  ARRAY[
    'Entry age 18 to 65 years',
    '48 months pre-existing waiting period',
    'Hospital cash benefit available'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
),
(
  'hlt-icici-lombard-complete-health-2026', 'health', 'ICICI Lombard', 'Complete Health Insurance',
  'All-in-one plan with OPD and wellness',
  14600.00, 'yearly',
  500000, 5000000, 2000000,
  18, 65,
  jsonb_build_object(
    'room_rent_limit', 'No limit',
    'pre_existing_coverage_months', 24,
    'maternity_cover', true,
    'opd_cover', true,
    'no_claim_bonus_pct', 50,
    'restore_benefit', true,
    'free_health_checkup', true,
    'wellness_program', true
  ),
  jsonb_build_object(
    'in_patient_hospitalization', true,
    'pre_hospitalization_days', 90,
    'post_hospitalization_days', 180,
    'day_care_procedures', true,
    'domiciliary', true,
    'organ_donor', true
  ),
  ARRAY[
    'Pre-existing conditions for first 24 months',
    'Wellness rewards capped annually'
  ],
  ARRAY[
    'Entry age 18 to 65 years',
    '24 months pre-existing waiting period',
    'Wellness and OPD included'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
)
on conflict (product_key) do nothing;


-- ============================================================
-- 7. Seed: Motor Insurance Reference (Demo) Data
-- ============================================================

insert into public.insurance_products (
  product_key, product_type, provider, product_name, tagline,
  base_premium, premium_frequency,
  sum_insured_min, sum_insured_max, sum_insured_default,
  entry_age_min, entry_age_max,
  features, coverage_details, exclusions, eligibility_criteria,
  data_classification, source, source_url
) values
(
  'mot-new-india-comprehensive-2026', 'motor', 'New India Assurance', 'Comprehensive Private Car',
  'Govt-backed PSU with widest cashless garage network',
  9850.00, 'yearly',
  500000, 5000000, 1200000,
  18, null,
  jsonb_build_object(
    'vehicle_type', 'private_car',
    'zero_depreciation_available', true,
    'roadside_assistance', true,
    'engine_protection_available', true,
    'key_replacement', true,
    'personal_accident_cover', 1500000,
    'third_party_property_damage', 750000
  ),
  jsonb_build_object(
    'own_damage_cover', true,
    'third_party_cover', true,
    'personal_accident_driver', true,
    'legal_liability', true,
    'towing_cover', true
  ),
  ARRAY[
    'Driving under influence excluded',
    'Commercial usage excluded',
    'Wear and tear excluded'
  ],
  ARRAY[
    'Private cars up to 15 years old',
    'Valid driving license required',
    'Add-ons available at extra premium'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
),
(
  'mot-tata-aig-auto-secure-2026', 'motor', 'TATA AIG', 'AutoSecure',
  'Zero depreciation as standard add-on',
  10650.00, 'yearly',
  400000, 6000000, 1500000,
  18, null,
  jsonb_build_object(
    'vehicle_type', 'private_car',
    'zero_depreciation_available', true,
    'zero_depreciation_included', true,
    'roadside_assistance', true,
    'engine_protection_available', true,
    'key_replacement', true,
    'consumables_cover', true,
    'personal_accident_cover', 2000000
  ),
  jsonb_build_object(
    'own_damage_cover', true,
    'third_party_cover', true,
    'personal_accident_driver', true,
    'legal_liability', true,
    'towing_cover', true
  ),
  ARRAY[
    'Driving under influence excluded',
    'Unauthorized drivers excluded'
  ],
  ARRAY[
    'Zero depreciation included',
    '24x7 roadside assistance',
    'Consumables cover included'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
),
(
  'mot-hdfc-ergo-car-insure-2026', 'motor', 'HDFC Ergo', 'Car Insure',
  'Quick claim settlement with digital survey option',
  11200.00, 'yearly',
  500000, 5000000, 1400000,
  18, null,
  jsonb_build_object(
    'vehicle_type', 'private_car',
    'zero_depreciation_available', true,
    'roadside_assistance', true,
    'engine_protection_available', true,
    'key_replacement', true,
    'loss_of_use_benefit', true,
    'personal_accident_cover', 1500000,
    'digital_claim_survey', true
  ),
  jsonb_build_object(
    'own_damage_cover', true,
    'third_party_cover', true,
    'personal_accident_driver', true,
    'legal_liability', true,
    'towing_cover', true
  ),
  ARRAY[
    'Mechanical breakdown excluded',
    'Racing and speed testing excluded'
  ],
  ARRAY[
    'Digital claim survey option',
    'Express claim settlement',
    'No-claim bonus discount up to 50%'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
)
on conflict (product_key) do nothing;


-- ============================================================
-- 8. Seed: Life Insurance Reference (Demo) Data
-- ============================================================

insert into public.insurance_products (
  product_key, product_type, provider, product_name, tagline,
  base_premium, premium_frequency,
  sum_insured_min, sum_insured_max, sum_insured_default,
  entry_age_min, entry_age_max,
  features, coverage_details, exclusions, eligibility_criteria,
  data_classification, source, source_url
) values
(
  'lif-lic-tech-term-2026', 'life', 'LIC', 'Tech Term',
  'Online term plan from India\'s most trusted insurer',
  8499.00, 'yearly',
  5000000, 50000000, 10000000,
  18, 65,
  jsonb_build_object(
    'plan_type', 'pure_term',
    'policy_term_min_years', 10,
    'policy_term_max_years', 40,
    'premium_payment_term', 'regular',
    'critical_illness_rider_available', true,
    'accidental_death_rider_available', true,
    'return_of_premium_option', true,
    'smoker_differential_premium', true
  ),
  jsonb_build_object(
    'death_benefit', true,
    'maturity_benefit_base', false,
    'loan_option', false
  ),
  ARRAY[
    'Suicide within first 12 months excluded',
    'Intoxication exclusion applicable',
    'Hazardous occupations may require extra premium'
  ],
  ARRAY[
    'Entry age 18 to 65 years',
    'Policy term 10 to 40 years',
    'Min sum insured Rs. 50 lakh',
    'Medical examination required for high SI'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
),
(
  'lif-hdfc-life-click-2-protect-2026', 'life', 'HDFC Life', 'Click 2 Protect Life',
  'Customizable term plan with 3 plan options',
  9250.00, 'yearly',
  5000000, 40000000, 10000000,
  18, 65,
  jsonb_build_object(
    'plan_type', 'term_with_options',
    'policy_term_min_years', 10,
    'policy_term_max_years', 40,
    'premium_payment_term', 'regular_limited_single',
    'critical_illness_rider_available', true,
    'accidental_death_rider_available', true,
    'return_of_premium_option', true,
    'income_benefit_option', true,
    'smoker_differential_premium', true
  ),
  jsonb_build_object(
    'death_benefit', true,
    'maturity_benefit_option', true,
    'loan_option', false
  ),
  ARRAY[
    'Suicide within first 12 months excluded',
    'Intoxication exclusion applicable',
    'War and civil commotion excluded'
  ],
  ARRAY[
    'Entry age 18 to 65 years',
    'Multiple plan options',
    'Income benefit on maturity available',
    'Income tax benefit under 80C & 10(10D)'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
),
(
  'lif-max-life-smart-secure-2026', 'life', 'Max Life', 'Smart Secure Plus',
  'Competitive online term rates with strong CSR',
  7899.00, 'yearly',
  2500000, 50000000, 10000000,
  18, 60,
  jsonb_build_object(
    'plan_type', 'pure_term',
    'policy_term_min_years', 10,
    'policy_term_max_years', 40,
    'premium_payment_term', 'regular',
    'critical_illness_rider_available', true,
    'accidental_death_rider_available', true,
    'return_of_premium_option', false,
    'smoker_differential_premium', true
  ),
  jsonb_build_object(
    'death_benefit', true,
    'maturity_benefit_base', false,
    'loan_option', false
  ),
  ARRAY[
    'Suicide within first 12 months excluded',
    'Intoxication exclusion applicable'
  ],
  ARRAY[
    'Entry age 18 to 60 years',
    'Online term plan',
    'Flexible policy terms',
    'Strong claim settlement ratio'
  ],
  'REFERENCE_DEMO',
  'NIRNAY_REFERENCE_DATA',
  null
)
on conflict (product_key) do nothing;


-- ============================================================
-- 9. Seed: Mutual Funds / SIP Reference (Demo) Data
-- ============================================================

insert into public.mutual_funds (
  product_key, provider, scheme_name,
  fund_category, sub_category, risk_level,
  nav, nav_date, expense_ratio,
  returns_1y, returns_3y, returns_5y,
  sip_min_amount, sip_frequency, lumpsum_min_amount,
  fund_manager, inception_date, aum_cr,
  exit_load, lock_in_period_months,
  features, benchmark,
  data_classification, source
) values
(
  'mf-axis-bluechip-growth', 'Axis Mutual Fund', 'Axis Bluechip Fund - Direct Plan - Growth',
  'equity', 'large_cap', 'moderately_high',
  58.4230, '2026-09-01', 1.02,
  18.42, 24.15, 16.82,
  500.00, 'monthly', 5000.00,
  'Shreyash Devalkar', '2013-01-01', 42500.00,
  '1% if redeemed within 12 months', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'stp_available', true,
    'swp_available', true,
    'eligible_80c', false
  ),
  'Nifty 50 TRI',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-parag-parikh-flexi-cap-growth', 'PPFAS Mutual Fund', 'Parag Parikh Flexi Cap Fund - Direct Plan - Growth',
  'equity', 'flexi_cap', 'very_high',
  82.1580, '2026-09-01', 0.77,
  22.15, 28.62, 21.45,
  1000.00, 'monthly', 10000.00,
  'Rajeev Thakkar', '2013-05-28', 55200.00,
  'Exit load 2% within 365 days, 1% 366-730 days', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'international_exposure', true,
    'eligible_80c', false
  ),
  'Nifty 500 TRI',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-sbi-small-cap-growth', 'SBI Mutual Fund', 'SBI Small Cap Fund - Direct Plan - Growth',
  'equity', 'small_cap', 'very_high',
  142.7890, '2026-09-01', 0.88,
  35.22, 38.10, 27.80,
  500.00, 'monthly', 5000.00,
  'R Srinivasan', '2013-09-09', 21800.00,
  '1% if redeemed within 365 days', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'eligible_80c', false
  ),
  'S&P BSE 250 SmallCap TRI',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-hdfc-mid-cap-growth', 'HDFC Mutual Fund', 'HDFC Mid-Cap Opportunities Fund - Direct - Growth',
  'equity', 'mid_cap', 'very_high',
  98.4500, '2026-09-01', 0.96,
  28.60, 32.80, 23.55,
  500.00, 'monthly', 5000.00,
  'Anil Bamboli', '2013-06-01', 38700.00,
  '1% if redeemed within 365 days', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'eligible_80c', false
  ),
  'Nifty Midcap 150 TRI',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-uti-nifty-index-growth', 'UTI Mutual Fund', 'UTI Nifty 50 Index Fund - Direct Plan - Growth',
  'index', 'nifty_50', 'moderately_high',
  212.3340, '2026-09-01', 0.12,
  16.80, 21.42, 14.60,
  500.00, 'monthly', 5000.00,
  'Sharwan Kumar Goyal', '2013-01-01', 11500.00,
  '0.25% if redeemed within 15 days', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'index_fund', true,
    'low_expense_ratio', true,
    'eligible_80c', false
  ),
  'Nifty 50 TRI',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-axis-liquid-growth', 'Axis Mutual Fund', 'Axis Liquid Fund - Direct Plan - Growth',
  'liquid', null, 'low',
  4512.8500, '2026-09-01', 0.18,
  6.85, 6.12, 5.80,
  100.00, 'monthly', 500.00,
  'Devang Shah', '2012-05-01', 28900.00,
  '0.007% if redeemed within 7 days', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'instant_redemption_available', true,
    'low_risk', true,
    'eligible_80c', false
  ),
  'CRISIL Liquid Fund Index',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-icici-balanced-advantage-growth', 'ICICI Prudential', 'ICICI Prudential Balanced Advantage Fund - Direct',
  'hybrid', 'dynamic_asset_allocation', 'moderate',
  72.4000, '2026-09-01', 0.72,
  14.20, 17.80, 13.10,
  500.00, 'monthly', 5000.00,
  'Rajat Chandak', '2013-06-01', 48600.00,
  '1% if redeemed within 12 months', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'dynamic_asset_allocation', true,
    'eligible_80c', false
  ),
  'CRISIL Hybrid 35+65 Aggressive',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-sbi-elss-tax-gain-growth', 'SBI Mutual Fund', 'SBI Long Term Equity Fund (ELSS) - Direct - Growth',
  'elss', 'tax_saver', 'very_high',
  382.1000, '2026-09-01', 0.84,
  19.85, 25.40, 17.20,
  500.00, 'monthly', 5000.00,
  'R Srinivasan', '2013-01-01', 32400.00,
  'Exit load 1% within 365 days', 36,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'eligible_80c', true,
    'section_80c_limit', 150000,
    'lock_in_months', 36
  ),
  'S&P BSE 200 TRI',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
),
(
  'mf-kotak-gold-etf-growth', 'Kotak Mutual Fund', 'Kotak Gold Fund - Direct Plan - Growth',
  'gold', null, 'moderately_low',
  28.7210, '2026-09-01', 0.55,
  8.40, 12.60, 10.80,
  500.00, 'monthly', 5000.00,
  'Devender Singhal', '2017-03-22', 6800.00,
  '1% if redeemed within 90 days', 0,
  jsonb_build_object(
    'direct_plan', true,
    'regular_plan_available', true,
    'dividend_plan_available', true,
    'sip_available', true,
    'hedge_against_inflation', true,
    'eligible_80c', false
  ),
  'Domestic Price of Gold',
  'REFERENCE_DEMO', 'NIRNAY_REFERENCE_DATA'
)
on conflict (product_key) do nothing;
