-- ============================================================
-- NIRNAY — Migration: Phase 7 Decision Execution & Storage
-- Creates decision_records for persisting user intent
-- ============================================================

create table if not exists public.decision_records (
  id bigint generated by default as identity primary key,

  user_id text not null
    references public.user_profiles(user_id)
    on delete cascade,

  product_id text not null,

  product_type text not null
    check (
      product_type in ('insurance', 'investment')
    ),

  status text not null default 'saved'
    check (
      status in ('saved', 'dismissed')
    ),

  suitability_score integer
    check (
      suitability_score is null
      or (suitability_score >= 0 and suitability_score <= 100)
    ),

  decision_context jsonb not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint decision_unique_active_per_user 
    unique (user_id, product_id)
);

-- Indexes
create index if not exists idx_decision_records_user_id
  on public.decision_records(user_id);

-- Updated_at trigger
drop trigger if exists set_decision_records_updated_at
on public.decision_records;

create trigger set_decision_records_updated_at
before update on public.decision_records
for each row
execute function public.set_updated_at();

-- ============================================================
-- Enable Row Level Security
-- ============================================================

alter table public.decision_records
  enable row level security;

-- ============================================================
-- RLS Policies
-- ============================================================

drop policy if exists "Users can select their own decision records"
on public.decision_records;

create policy "Users can select their own decision records"
on public.decision_records
for select
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);

drop policy if exists "Users can insert their own decision records"
on public.decision_records;

create policy "Users can insert their own decision records"
on public.decision_records
for insert
to authenticated
with check (
  user_id = (auth.jwt() ->> 'sub')
);

drop policy if exists "Users can update their own decision records"
on public.decision_records;

create policy "Users can update their own decision records"
on public.decision_records
for update
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
)
with check (
  user_id = (auth.jwt() ->> 'sub')
);

drop policy if exists "Users can delete their own decision records"
on public.decision_records;

create policy "Users can delete their own decision records"
on public.decision_records
for delete
to authenticated
using (
  user_id = (auth.jwt() ->> 'sub')
);
