-- ============================================================
-- Migration 20260910000002
-- Add budgets table
-- ============================================================

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id text not null references public.user_profiles(user_id) on delete cascade,
  
  category text not null,
  amount numeric(14,2) not null check (amount >= 0),
  
  period_month int not null check (period_month between 1 and 12),
  period_year int not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- One budget per category per month per user
  constraint unique_user_category_period unique (user_id, category, period_month, period_year)
);

create index if not exists idx_budgets_user_id on public.budgets(user_id);
create index if not exists idx_budgets_period on public.budgets(user_id, period_year, period_month);

drop trigger if exists set_budgets_updated_at on public.budgets;
create trigger set_budgets_updated_at
before update on public.budgets
for each row
execute function public.set_updated_at();

alter table public.budgets enable row level security;

drop policy if exists "Users can select their own budgets" on public.budgets;
create policy "Users can select their own budgets" on public.budgets
for select to authenticated
using (user_id = (auth.jwt() ->> 'sub'));

drop policy if exists "Users can insert their own budgets" on public.budgets;
create policy "Users can insert their own budgets" on public.budgets
for insert to authenticated
with check (user_id = (auth.jwt() ->> 'sub'));

drop policy if exists "Users can update their own budgets" on public.budgets;
create policy "Users can update their own budgets" on public.budgets
for update to authenticated
using (user_id = (auth.jwt() ->> 'sub'))
with check (user_id = (auth.jwt() ->> 'sub'));

drop policy if exists "Users can delete their own budgets" on public.budgets;
create policy "Users can delete their own budgets" on public.budgets
for delete to authenticated
using (user_id = (auth.jwt() ->> 'sub'));
