-- ============================================================
-- Migration 20260910000001
-- Add transactions table
-- ============================================================

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id text not null references public.user_profiles(user_id) on delete cascade,
  
  transaction_date date not null,
  description text not null,
  
  amount numeric(14,2) not null check (amount > 0),
  type text not null check (type in ('income', 'expense')),
  category text not null,
  note text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Indexes for efficient querying by user and date
create index if not exists idx_transactions_user_id on public.transactions(user_id);
create index if not exists idx_transactions_date on public.transactions(user_id, transaction_date desc);

-- Auto-update updated_at timestamp
drop trigger if exists set_transactions_updated_at on public.transactions;
create trigger set_transactions_updated_at
before update on public.transactions
for each row
execute function public.set_updated_at();

-- Enable RLS
alter table public.transactions enable row level security;

-- Policies for full CRUD scoped to the authenticated user
drop policy if exists "Users can select their own transactions" on public.transactions;
create policy "Users can select their own transactions"
on public.transactions for select to authenticated
using (user_id = (auth.jwt() ->> 'sub'));

drop policy if exists "Users can insert their own transactions" on public.transactions;
create policy "Users can insert their own transactions"
on public.transactions for insert to authenticated
with check (user_id = (auth.jwt() ->> 'sub'));

drop policy if exists "Users can update their own transactions" on public.transactions;
create policy "Users can update their own transactions"
on public.transactions for update to authenticated
using (user_id = (auth.jwt() ->> 'sub'))
with check (user_id = (auth.jwt() ->> 'sub'));

drop policy if exists "Users can delete their own transactions" on public.transactions;
create policy "Users can delete their own transactions"
on public.transactions for delete to authenticated
using (user_id = (auth.jwt() ->> 'sub'));
